language: python
python:
- "3.6.1"
node_js:
- "10.3.0"
sudo: true



script:
  - npm install -g serverless
  - npm install --save serverless-python-requirements

deploy:
  skip_cleanup: true
  provider: script
  script: serverless deploy
  on:
    branch: cit
