language: python
python:
- "3.6.1"

script:
  - pip install -r requirements.txt ./

deploy:
  skip_cleanup: true
  provider: lambda
  function_name: "recommendmeFE"
  region: "us-east-2"
  role: "arn:aws:iam::627490492245:role/service-role/testLambdaRole"
  runtime: "python3.6"
  handler_name: "universal"
  module_name: "lambda"
  on:
    branch: cit
